language: objective-c
cache:
skip_bundle_clean: true
osx_image: xcode7.2
before_script:
- rvm get head
script:
- xctool test -workspace MeiQianZheng.xcworkspace -scheme MeiQianZhengTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
